version: "3.9"

services:
  postgres:
    container_name: postgresql
    restart: always
    image: postgres:13.2
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5444:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    networks:
      - cache-backend
  redis:
    container_name: cache-redis
#    command: redis-server --requirepass password --appendonly yes
    image: redis:6.2.1
    ports:
      - 127.0.0.1:6388:6379
    networks:
      - cache-backend

volumes:
  db_data:

networks:
  cache-backend:
    name: test-cache-backend
